"use strict";
exports.__esModule = true;
var ReduxUtils_1 = require("Libraries/Core/Utils/ReduxUtils");
var GROUP = 'GROUP_';
exports.LOAD_GROUP = GROUP + ReduxUtils_1.EActionTypes.LOAD_ITEM;
exports.LIST_GROUPS = GROUP + ReduxUtils_1.EActionTypes.LOAD_LIST;
exports.CREATE_GROUP = GROUP + ReduxUtils_1.EActionTypes.CREATE_ITEM;
exports.JOIN_GROUP = GROUP + "JOIN";
exports.LEAVE_GROUP = GROUP + "LEAVE";
exports.DELETE_GROUP = GROUP + "DELETE";
exports.LOAD_MEMBERS = GROUP + "MEMBERS" + ReduxUtils_1.EActionTypes.LOAD_LIST;
